### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by fernand0dias** [Drewsapple/sveltekit-siwe#1]
I was needing a demo template of how to put sveltekit, auth/core, auth/sveltekit and wagmi/core together. The repository ran easily and the project structure served as a good example. Thanks.

**Comment by Drewsapple** [comment]
FYI, this is a super alpha-level test, it works in dev mode, but builds fail due to how node polyfills are resolved. I have an issue open in the vite-plugin-node-polyfills repository here: https://github.com/voracious/vite-plugin-node-polyfills/issues/13 if you want to track updates.
